# Generated by Django 2.2 on 2020-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200117_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_code',
            field=models.CharField(default='AAA111', max_length=20),
            preserve_default=False,
        ),
    ]
