# Generated by Django 2.2 on 2020-01-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refund',
            name='rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
