# Generated by Django 2.2 on 2020-01-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200117_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
